allow a custom config
terrycain/sanic-json-logging pull request #133
Opened 2021-08-26 23:22 UTC by digitalkaoz

adds the ability to e.g. set custom formatters

2021-08-29 17:51 UTC, terrycain requested changes

2021-08-29 17:51 UTC, terrycain commented on sanic_json_logging/__init__.py
> +    config["formatters"]["generic"]["context"] = context_var
If a user can override the value of `config`, they could omit generic and context dict's, can you add some error checking to add those in if they don't exist.

2021-08-29 17:51 UTC, terrycain commented
Overall looks good :smile:

2021-08-30 09:09 UTC, terrycain approved these changes
I cant help think there's a nicer way do to it, but I cant think of any so am happy :D

2021-08-30 09:10 UTC, merged

2021-08-30 09:15 UTC, digitalkaoz commented
@terrycain i wasnt perfectly happy either ;)